### ISSUE TITLE
과제 01: JVM은 무엇이며 자바 코드는 어떻게 실행하는 것인가.

### ISSUE THREAD

**Issue by yhames** [spring-for-hitchhiker/java-study#1]
## 목표

자바 소스 파일(.java)을 JVM으로 실행하는 과정 이해하기.

## 학습 내용

* JVM이란 무엇인가
* 컴파일 하는 방법
* 실행하는 방법
* 바이트코드란 무엇인가
* JIT 컴파일러란 무엇이며 어떻게 동작하는지
* JVM 구성 요소
* JDK와 JRE의 차이

**Comment by yhames** [comment]
- 바이트코드와 바이너리코드의 차이가 무엇인가요?
- 자바는 컴파일 언어인가요 인터프리터 언어인가요?

**Comment by yhames** [comment]
자바는 컴파일 언어인가요 인터프리터 언어인가요?

**Comment by yhames** [comment]
JVM의 구성요소 중에 JNI는 무엇이고 언제, 왜 사용하나요?

**Comment by yhames** [comment]
JVM의 구성요소 중 클래스로더에서 초기화 단계를 수행할 때 멀티쓰레드 환경을 고려하지 않으면 왜 동시성 문제가 발생하나요? 해결방법은 무엇이 있나요?

**Comment by AreSain** [comment]
클래스 로더의 세가지 원칙은 무엇인가요?

**Comment by KenWR** [comment]
javac 라는 컴파일러가있는데 왜 JIT를 사용하는가?

**Comment by ybs132** [comment]
JIT 컴파일 과정에서 최적화는 어떤 방식으로 진행되나요?
