### ISSUE TITLE
과제 03: 연산자

### ISSUE THREAD

**Issue by yhames** [spring-for-hitchhiker/java-study#3]
## 목표

자바가 제공하는 다양한 연산자를 학습하세요.

## 학습 내용

* 산술 연산자
* 비트 연산자
* 관계 연산자
* 논리 연산자
* instanceof
* assignment(=) operator
* 화살표(->) 연산자
* 3항 연산자
* 연산자 우선 순위
* (optional) Java 13. switch 연산자

**Comment by yhames** [comment]
래퍼런스 타입 변수도 연산자를 사용할 수 있나요? (`+` for `String` 클래스)
연산자 오버로딩이 가능한가요?

**Comment by yhames** [comment]
`>>>` 연산자와 `>>` 연산자의 차이가 무엇인가요? `<<<` 연산자는 왜 없나요?

**Comment by yhames** [comment]
`instanceof`를 원시타입에 사용할 수 있나요? 사용하려면 어떻게 해야하나요?

**Comment by ybs132** [comment]
화살표 연산자를 이용하여 생성한 함수를 사용하는 간단한 예시를 알려주세요 !

**Comment by KenWR** [comment]
비트연산으로 오버플로우가 일어날 수 있나요?
