### ISSUE TITLE
과제 04: 제어문 (실습)

### ISSUE THREAD

**Issue by yhames** [spring-for-hitchhiker/java-study#4]
## 목표

자바가 제공하는 제어문을 학습하세요.

## 학습 내용

* 선택문
* 반복문

### 실습 00. JUnit 5 학습하세요.
* 인텔리J, 이클립스, VSCode에서 JUnit5로 테스트 코드 작성하는 방법에 익숙해 질 것.
* [더 자바, 테스트](https://www.inflearn.com/course/the-java-application-test?inst=86d1fbb8) 강의도 있으니 참고

### 실습 01. live-study 대시 보드를 만드는 코드를 작성하세요.
* 깃헙 이슈 1번부터 18번까지 댓글을 순회하며 댓글을 남긴 사용자를 체크 할 것.
* 참여율을 계산하세요. 총 18회에 중에 몇 %를 참여했는지 소숫점 두자리가지 보여줄 것.
* live-study 깃허브 링크 : [https://github.com/whiteship/live-study](https://github.com/whiteship/live-study)
* [Github 자바 라이브러리](https://github-api.kohsuke.org/)를 사용하면 편리합니다.
* 깃헙 API를 익명으로 호출하는데 제한이 있기 때문에 본인의 깃헙 프로젝트에 이슈를 만들고 테스트를 하시면 더 자주 테스트할 수 있습니다.

### 실습 02. LinkedList를 구현하세요.
* LinkedList에 대해 공부하세요.
* 정수를 저장하는 ListNode 클래스를 구현하세요.
* ListNode add(ListNode head, ListNode nodeToAdd, int position)를 구현하세요.
* ListNode remove(ListNode head, int positionToRemove)를 구현하세요.
* boolean contains(ListNode head, ListNode nodeTocheck)를 구현하세요.

### 실습 03. 과제 3. Stack을 구현하세요.
* int 배열을 사용해서 정수를 저장하는 Stack을 구현하세요.
* void push(int data)를 구현하세요.
* int pop()을 구현하세요.

### 실습 04. 앞서 만든 ListNode를 사용해서 Stack을 구현하세요.
* ListNode head를 가지고 있는 ListNodeStack 클래스를 구현하세요.
* void push(int data)를 구현하세요.
* int pop()을 구현하세요.

### 실습 05. Queue를 구현하세요.
* 배열을 사용해서 한번
* ListNode를 사용해서 한번.

**Comment by AreSain** [comment]
실습 1번 테스트 용도입니다 :)

**Comment by AreSain** [comment]
중복 제거 테스트 입니다 :)

**Comment by KenWR** [comment]
Junit 을 왜 사용하나요?

**Comment by AreSain** [comment]
테스트 주도 개발(Test Driven Development)의 장단점이 뭔가요?
