### ISSUE TITLE
과제 05: 클래스 (실습)

### ISSUE THREAD

**Issue by yhames** [spring-for-hitchhiker/java-study#5]
## 목표

자바의 Class에 대해 학습하세요.

## 학습 내용

* 클래스 정의하는 방법
* 객체 만드는 방법 (new 키워드 이해하기)
* 메소드 정의하는 방법
* 생성자 정의하는 방법
* this 키워드 이해하기

## 실습 내용

* int 값을 가지고 있는 이진 트리를 나타내는 Node 라는 클래스를 정의하세요.
* int value, Node left, right를 가지고 있어야 합니다.
* BinrayTree라는 클래스를 정의하고 주어진 노드를 기준으로 출력하는 bfs(Node node)와 dfs(Node node) 메소드를 구현하세요.
* DFS는 왼쪽, 루트, 오른쪽 순으로 순회하세요.

**Comment by AreSain** [comment]
클래스들은 가변적이여야 하는 매우 타당한 이유가 있지 않는 한 반드시 불변으로 만들어야 한다. 만약 클래스를 불변으로 만드는 것이 불가능하다면, 가능한 변경 가능성을 최소화하라.- Effective Java - 라는 말이 있습니다.
불변 객체와 그 장점이 무엇인가요?

**Comment by AreSain** [comment]
this 참조변수를 클래스 메소드에서도 사용할 수 있나요?

**Comment by AreSain** [comment]
자바에서 말하는 다형성(polymorphism)이 무엇이며, 참조변수에서 다형성은 어떻게 사용되나요?

**Comment by yhames** [comment]
메서드와 함수의 차이가 무엇인가요? 필드가 무엇인가요?
클래스, 객체, 인스턴스의 차이가 무엇인가요?

**Comment by yhames** [comment]
클래스 안에 클래스를 선언해도 되나요?

**Comment by yhames** [comment]
클래스를 생성했을 때 클래스의 정보들이 저장되는 곳은 어디인가요?
인스턴스를 생성했을 때 해당 인스턴스에 대한 정보는 어디에 저장되나요?
static 클래스에서 일반 클래스의 인스턴스를 생성할 수 있나요? 안된다면 그 이유는 무엇인가요?

**Comment by ybs132** [comment]
필드와 멤버는 다른 개념인가요?
