### ISSUE TITLE
과제 06: 상속

### ISSUE THREAD

**Issue by yhames** [spring-for-hitchhiker/java-study#6]
## 목표

자바의 상속에 대해 학습하세요.

## 학습 내용

* 자바 상속의 특징
* super 키워드
* 메소드 오버라이딩
* 다이나믹 메소드 디스패치 (Dynamic Method Dispatch)
* 추상 클래스
* final 키워드
* Object 클래스

**Comment by AreSain** [comment]
자바에서 말하는 다형성(polymorphism)이 무엇이며, 참조변수에서 다형성은 어떻게 사용되나요?

**Comment by AreSain** [comment]
자식 클래스는 부모 클래스의 private나 default 접근 제어자가 붙은 메소드, 변수에 접근할 수 없습니다.
그럼 그냥 이름 똑같은 변수나 메소드를 오버라이딩 안하고 그냥 만들어 써도 되나요?

**Comment by yhames** [comment]
2개 이상의 부모 클래스를 상속받을 수 있나요? 안된다면 어떤 이유 때문에 안되게 만들었나요?

**Comment by yhames** [comment]
상속 관계에서 부모 클래스를 더 자세하게 작성해야하나요 자식 클래스를 더 자세하게 작성해야하나요?

**Comment by yhames** [comment]
하위 클래스(자식 클래스)를 생성하면 상위 클래스(부모 클래스)의 필드와 메서드를 메모리 영역에 복사해서 사용하나요? 아니면 참조해서 사용하나요?
하위 클래스의 인스턴스를 생성하고 부모 클래스의 필드나 메서드에 접근할 때 메모리 할당과 참조가 어떤식으로 되는지 궁금합니다.

**Comment by KenWR** [comment]
부모가 자식클래스에 접근할 수 있나요?

**Comment by KenWR** [comment]
추상 클래스에서의 상속은 어떻게 이루어지나요?
