### ISSUE TITLE
과제 08: 인터페이스

### ISSUE THREAD

**Issue by yhames** [spring-for-hitchhiker/java-study#8]
## 목표

자바의 인터페이스에 대해 학습하세요.

## 학습 내용

* 인터페이스 정의하는 방법
* 인터페이스 구현하는 방법
* 인터페이스 레퍼런스를 통해 구현체를 사용하는 방법
* 인터페이스 상속
* 인터페이스의 기본 메소드 (Default Method), 자바 8
* 인터페이스의 static 메소드, 자바 8
* 인터페이스의 private 메소드, 자바 9

**Comment by AreSain** [comment]
factory 메소드가 무엇인가요?

**Comment by AreSain** [comment]
Default 메소드와 static 메소드에서 메소드 이름이 같은 경우
클래스, 상속받은 sub interface, 부모 interface, 세개 중 어떤 순서대로 우선적으로 사용되나요?

**Comment by AreSain** [comment]
static 메소드에서 static 메소드나 변수만 쓸 수 있는 이유가 뭔가요?

**Comment by yhames** [comment]
> factory 메소드가 무엇인가요?

https://refactoring.guru/ko/design-patterns/factory-method
