### ISSUE TITLE
과제 09: 예외 처리

### ISSUE THREAD

**Issue by yhames** [spring-for-hitchhiker/java-study#9]
## 목표

자바의 예외 처리에 대해 학습하세요.

## 학습 내용

* 자바에서 예외 처리 방법 (try, catch, throw, throws, finally)
* 자바가 제공하는 예외 계층 구조
* Exception과 Error의 차이는?
* RuntimeException과 RE가 아닌 것의 차이는?
* 커스텀한 예외 만드는 방법

**Comment by yhames** [comment]
`try-with-resource`에서 자원을 사용하는 예시가 무엇이 있나요?

**Comment by yhames** [comment]
예외처리 전략에 대해 알려주세요.
* 커스텀 예외를 만들 때 어떤 상황에서 `Unchecked`를 써야하고 어떤 상황에서 `Checked`를 써야하나요?
* `Checked` 예외는 반드시 `try-catch`문을 사용해서 "처리"해야한다고 하는데, 처리한다는 것이 정확하게 어떤 행위(혹은 코드)를 의미하나요? 예외처리하는 방법에 대해 알려주세요

**Comment by yhames** [comment]
`e.printStackTrace()`가 무엇인가요?

**Comment by yhames** [comment]
예외처리를 그냥 로직으로 사용하지 않고, `Exception`을 사용하는 이유는 뭔가요?

예를 들어 `c`언어에서는 `open()` 함수로 파일을 열고 반환값을 사용하여 정상적으로 파일이 열린 것인지 확인을 하는데,
`java`에서는 `File`클래스를 사용하면 `IOException`을 `throw`하는 것으로 확인을 합니다.
어떤 장점이 있어서 이런 방법을 채택한 것인가요?

**Comment by AreSain** [comment]
Exception을 계속 throw 하다보면 결국 메인까지 올텐데, 그마저도 throw하면 어떻게 처리하는지 궁금합니다.
